name: transaction_presentation
description: Transaction presentation layer
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  auto_route:
  flutter_bloc:
  get_it:
  injectable:

  equatable:
  cupertino_icons:

  # Local packages
  navigation:
    path: ../../../navigation
  shared:
    path: ../../../shared
  widgets:
    path: ../../../core/widgets
  blocfx:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner:
  auto_route_generator:
  injectable_generator:

flutter:
