name: database
description: "Database module for secure credential storage"
version: 0.0.1
homepage:
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage:
  injectable:
  get_it:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  injectable_generator:

flutter:
