name: app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2
  flutter:

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  injectable:
  auto_route:
  get_it:
  shared:
    path: ../packages/shared
  network:
    path: ../packages/core/network
  navigation:
    path: ../packages/navigation

  database:
    path: ../packages/core/database

  # local packages
  onboarding_presentation:
    path: ../packages/features/onboarding/presentation
  login_presentation:
    path: ../packages/features/login/presentation
  login_domain:
    path: ../packages/features/login/domain
  login_data:
    path: ../packages/features/login/data
  register_presentation:
    path: ../packages/features/register/presentation
  main_presentation:
    path: ../packages/features/main/presentation
  home_presentation:
    path: ../packages/features/home/presentation
  profile_presentation:
    path: ../packages/features/profile/presentation
  transaction_presentation:
    path: ../packages/features/transaction/presentation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  injectable_generator:
  auto_route_generator:

flutter:
  uses-material-design: true
