name: widgets
description: "A new Flutter module project."
publish_to: none

environment:
  sdk: ^3.9.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  formz:

  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.widgets
    iosBundleIdentifier: com.example.widgets
