name: network
description: "A new Flutter module project."

environment:
  sdk: ^3.9.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # HTTP Client
  dio:
  retrofit:
  pretty_dio_logger:

  # JSON Serialization
  json_annotation:

  # Dependency Injection
  get_it:
  injectable:

  database:
    path: ../database

  # Utils
  logger:
  dartz:

  # analytics
  analytics:
    path: ../analytics

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner:
  injectable_generator:
  retrofit_generator:
  json_serializable:

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.network
    iosBundleIdentifier: com.example.network
